name: tasks
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  flutter_screenutil: ^5.9.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  dio: ^5.3.4
  get_it: ^7.6.4
  injectable: ^2.3.2
  go_router: ^13.0.0
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
  build_runner: ^2.4.6
  injectable_generator: ^2.4.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true
